FROM ubuntu:jammy

RUN apt update && apt upgrade -y
RUN apt install python3.10 python3.10-dev python3-pip -y
RUN apt install tmux -y
RUN apt install git -y
RUN apt install nano wget curl iproute2 -y
RUN apt install python-is-python3 -y
WORKDIR "/root"